//! Node: `cxx:Test:Luau.UnitTest:tests/FragmentAutocomplete.test.cpp:3106:fragment_autocomplete_ice_caused_by_mixed_mode_use`
//! Source: `tests/FragmentAutocomplete.test.cpp`

#[cfg(test)]
#[test]
fn fragment_autocomplete_ice_caused_by_mixed_mode_use() {
    use crate::records::fragment_autocomplete_builtins_fixture::FragmentAutocompleteBuiltinsFixture;
    use alloc::boxed::Box;
    use alloc::string::String;
    use luaur_analysis::records::fragment_autocomplete_status_result::FragmentAutocompleteStatusResult;

    // C++ builds this source by concatenating string literals with explicit
    // escape sequences (`\n`, `\t`). Transcribed below with a literal tab and
    // newlines so the bytes match exactly.
    let source = String::from("--[[\n\tPackage link auto-generated by Rotriever\n]]\nlocal PackageIndex = script.Parent._Index\n\nlocal Package = ")
        + "require(PackageIndex[\"ReactOtter\"][\"ReactOtter\"])\n\nexport type Goal = Package.Goal\nexport type SpringOptions "
        + "= Package.SpringOptions\n\n\nreturn Pa@1";

    let mut fixture = FragmentAutocompleteBuiltinsFixture::default();
    fixture.base.autocomplete_fragment_in_both_solvers(
        &source,
        &source,
        '1',
        Box::new(|_: &mut FragmentAutocompleteStatusResult| {}),
        None,
    );
    fixture.base.autocomplete_fragment_in_both_solvers(
        &source,
        &source,
        '1',
        Box::new(|_: &mut FragmentAutocompleteStatusResult| {}),
        None,
    );
}
